services:
  - type: web
    name: russian-quiz-bot
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: russian-quiz-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false

databases:
  - name: russian-quiz-db
    plan: free 